window.XJB_LOAD_TRANSLATE = function (_status, lib, game, ui, get, ai) {
    let skill = {
        "xin_jincui": "尽瘁",
        "xin_jincui_info": "每轮限一次，回合开始前，你可以弃置你全域内两张牌，然后将等量火【杀】置于武将牌上。当前回合后你额外执行一个回合。",
        "xin_chushi": "出师",
        "xin_chushi_info": "出牌阶段限一次，你可选择是否对一名角色依次使用你武将牌上的所有牌。",
        "xin_yeling": "谒陵",
        "xin_yeling_info": "锁定技，你的准备阶段，你可以进行一次判定，你使用与判定牌同名的<a>残牌</a>。</b>",
        "xin_huanshi": "蓄发",
        "xin_huanshi_info": "当一张牌判定牌生效前，你可以将任意张牌置于牌堆顶，然后从牌堆底摸等量张牌。",
        "xin_bianzhu": "权揽",
        "xin_bianzhu_info": "一张梅花判定牌生效后，若场上仍有谒陵技能的角色，你可额外进行一个回合。你第一次发动该技能后，你获得如下效果：<br>你每对一名角色使用一张非装备牌，其使用1～3张与此牌同名的残牌</b>。",
        "xin_zhabing": "诈病",
        "xin_zhabing_info": "<b>限定技</b>，你的回合开始时，若你已受伤，你可以跳过此回合并获得技能“权揽”。场上所有其他角色视为拥有\"谒陵\"直到其第一次发动。",
        "xin_huzhu": "护主",
        "xin_huzhu_info": "当一名其他角色使用【杀】指定目标时，你可以选择以下一项执行之：⑴弃置一张牌，目标角色摸两张牌;⑵失去一点体力，目标角色获得1个“护”。 ",
        "xin_huzhu2": "护主",
        "xin_huzhu2_info": "<i>护：你可以在需要时，视为使用或打出一张【闪】。若此做，你摸一张牌并移去1个“护”。</i> ",
        "xin_xiongli": "凶力",
        "xin_xiongli_info": "出牌阶段限一次，你可以对任意名其他角色造成一点破甲伤害，若此做，对自己使用等量张残【杀】。</b>",
        "xin_mousheng": "谋圣",
        "xin_mousheng_info": "锁定技，你亮出拼点牌时，你拼点牌点数+X(X为游戏轮数)",
        "xin_bingjie": "秉节",
        "xin_bingjie_info": "1.一名角色准备阶段前，你可以弃置所有手牌，你令该角色将手牌调至体力上限<br>2.你受到一点伤害后，你可令一名角色将手牌调至体力上限。<br>因该技能获得的牌均记为\"留香\"。",
        "xin_liuxiang": "留香",
        "xin_liuxiang_info": "一名角色每失去X次\"留香\"牌后，你可以令其恢复一点体力值。(X为其体力值)",
        "xin_ziruo": "自若",
        "xin_ziruo_info": "当你成为其他角色的牌的目标时，你可为此牌减少任意名未横置的目标，然后这些目标横置。",
        "xin_fengtian": "挥鞭",
        "xin_fengtian_info": "结束阶段/你杀死一名角色后，若你还有带有伤害标签的牌，你可以摸两张牌然后额外执行一个出牌阶段。",
        "xin_niepan": "涅槃",
        "xin_niepan_info": "出牌阶段限两次时，你若你手牌数为奇数，你可回复一点体力并摸一张牌;手牌数为偶数，你可以失去一点体力并摸三张牌。",
        "xin_tianming": "天命",
        "xin_tianming_info": "锁定技，当你失去一张区域的牌后，若你有未记录该牌的花色，你记录之并摸一张牌。",
        "xin_zulong": "祖龙",
        "xin_zulong_info": "当你体力值减少后，可以你获得一个技能。若此技能为觉醒技，则无视发动条件。",
        "xin_zaozhong": "遗计",
        "xin_zaozhong_info": "当你受到一点伤害后，你选择一名角色，其使用一张残【兵粮寸断】然后摸三张牌。",
        "xin_taoni": "讨逆",
        "xin_taoni_info": "出牌阶段限一次，你可以弃置一张♦️牌并选择一名未横置的角色，该角色横置然后你摸一张牌;你对已横置的角色使用牌无距离和次数限制。",
        "xin_jiang": "激昂",
        "xin_jiang_info": "当你造成伤害及受到伤害后，涉及的角色各摸X张牌(X为已横置的角色，X至多为3)",
        "xin_yingyi": "英义",
        "xin_yingyi_info": "君主技，锁定技，场上每有一名吴势力角色，你激昂的X值便+1。",
        "xin_qns": "急救",
        "xin_qns_info": "你可以将一张红色牌当做【桃】使用。若此时，你的手牌数<3，你摸一张牌。",
        "xin_whlw1": "帷幕",
        "xin_whlw1_info": "锁定技，当成为其他角色的目标时，你令来源使用两张对应的残牌。",
        "xin_whlw2": "完杀",
        "xin_whlw2_info": "锁定技，当有角色于你的回合内进入濒死阶段时，你获得其所有手牌。",
        "xin_htzjq2": "铁骑",
        "xin_htzjq2_info": "当你使用【杀】指定一名角色为目标后，你令其选择失去一点体力/体力上限。",
        "xjb_leijue": "雷诀",
        "xjb_leijue_info": "出牌阶段，你可以弃置一张黑桃牌，然后对一名角色造成1点雷属性伤害。",
        "xjb_xinsheng": "新生",
        "xjb_xinsheng_info": "出牌阶段，你可以弃置三张手牌令一名角色复活。",
        "xjb_lunhui": "灵愈",
        "xjb_lunhui_info": "当你濒死时，你可以恢复三点体力然后弃置全区域内两张牌。",
        "xin_lianhuan": "连环",
        "xin_lianhuan_info": "出牌阶段限一次，你可令X名角色横置或重置。(X为你的体力值)",
        "xjb_liuli": "流离",
        "xjb_liuli_info": "当你受到伤害前，你可交给另一名其他角色一张♦️牌，若此做，你令伤害来源改为这名角色并令其重新分配伤害(每名角色至多1点伤害)",
        "xjb_guose": "国色",
        "xjb_guose_info": "出牌阶段限一次，你可以选择一名判定区无牌的角色，然后你摸X张牌(X为场上的牌数)并将其中的非♦️牌当做任意一张延时锦囊牌置于其判定区内。",
        "xin_longpan": "龙蟠",
        "xin_longpan_info": "你的回合后，若你已有四种花色，你可以移去\"天命\"中的全部个花色，若此做，你令一名角色失去一点体力并摸四张牌。",
        "xin_enyuan": "恩怨",
        "xin_enyuan_info": "①当你一次因一名其他角色获得两张牌时，你可以令其摸一张牌;②当你受到伤害后，你可以令伤害来源失去等量点体力并获得其等量张牌。",
        "xjb_fuyi": "辅翼",
        "xjb_fuyi_info": "每轮开始时，你可以使用一张【逐鹿天下】。<br>一名角色每回合指定有装备的角色为唯一目标时，其可以交给你至少一张手牌(若为你则改为弃置)，其令此牌多指定等量个目标。",
        "xjb_sicuan": "倒置",
        "xjb_sicuan_info": "每轮限一次，你可令一名角色的两种事件颠倒进行",
        "xin_yingfa": "英发",
        "xin_yingfa_info": "出牌阶段限一次，你可以失去一点体力，令一名角色失去一种类型的所有牌，你随机获得其中一张牌。",
        "_xjb_remnantArea": "<font color=gold>残区</font>",
        "_xjb_remnantArea_info": "",
        "_UseHpCard": "<font color=gold>体力牌</font>",
        "_UseHpCard_info": "",
        "xjb_lingpiao": "灵票",
        "xjb_lingpiao_info": "一名其他角色灵力增加时，你可取消之，并用一张【灵力支票】代替。<br>产生【灵力支票】的消耗由此角色支付。",
        "xjb_guifan": "归返",
        "xjb_guifan_info": "出牌阶段，你可以读档。",
        "xjb_minglou": "铭镂",
        "xjb_minglou_info": "出牌阶段，你可以存档。",
        "xjb_soul_fuhua": "蝠化",
        "xjb_soul_fuhua_info": "人形状态技：<br>当你濒死时，你体力回复至1点并进入一轮蝙蝠状态。",
        "xin_xueqi": "血契",
        "xin_xueqi_info": "当你对一名角色造成伤害时，你可以与该角色交换体力牌。若此做，你指定一名角色进入<b description=[进入该空间后，灵力会全部转化为魔力，角色在其回合内使用牌混乱。]>血色空间</b>。",
        "xjb_soul_yiying": "移影",
        "xjb_soul_yiying_info": "蝙蝠状态技:<br>你可以在需要时，视为使用或打出一张【闪】。",
        "xjb_soul_chanter": "吟咏",
        "xjb_soul_chanter_info": "出牌阶段限一次，你可以弃置一张卡牌并进入<b description=[进入该空间后，灵力最大可以达到100Ch，在该区域内的的伤害会被魔力吸收，作用到角色上负收益翻倍。]>聚灵区</b>，然后你进行一次<b description=[打开技能编辑器，令系统在线编写并生成一个锁定技，你该技能对应的技能牌置于阵法区]>吟咏</b>。",
    }
    let soulCharacter = {
        xjb_Fuaipaiyi: "芙艾派依",
        xjb_xuemo: "布劳德",
        xjb_timer: "泰穆尔",
        xjb_chanter: "琪盎特儿",
        xjb_newCharacter: lib.config.xjb_newcharacter.name2,
        xjb_SoulBoss_zhankuang: "战狂魂使",
        xjb_SoulBoss_xuanfeng: "旋风魂使",
    }
    let xjbChracter = {
        "xin_fellow": "秦兵",
        "xjb_daqiao": "大乔",
        "xjb_sunce": "孙策",
        "xjb_guojia": "郭嘉",
        "xjbhan_caocao": "曹操",
        "xjbhan_xunyu": "荀彧",
        "xjb_pangtong": "庞统",
        "xjb_caocao": "曹操",
        "xjb_zhouyu": "周瑜",
        "xjb_liushan": "刘禅",
        "xjb_dianwei": "典韦",
        "xjb_ganning": "甘宁",
        "xjb_zhugeliang": "诸葛亮",
        "xjb_jin_simayi": "司马懿",
        "xjb_yingzheng": "嬴政",
        "xjb_fazheng": "法正",
        "xjb_jiaxu": "贾诩",
    }
    let characterSort = {
        xjb_chidan: '赤胆忠心',
        xjb_fengyun: '风云荟萃',
        xjb_zaiwu: '天命在吾',
        xjb_tiandu: '天妒英才',
        xjb_jincui: '鞠躬尽瘁',
        xjb_guijin: '三分归晋',
        xjb_huahao: '花好月圆',
        xjb_yangcheng: "养成武将",
        xjb_hunshi: "魂使集团",
        xjb_lingsu: "灵力复苏",
    }
    lib.translate = {
        ...lib.translate,
        ...skill,
        ...soulCharacter,
        ...xjbChracter,
        ...characterSort
    }
}